# Generated by Django 4.2.10 on 2024-02-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
